spring:
  datasource:
    url: jdbc:mysql://${DB_URL:localhost:3306}/${BD_SCHEMA:bonnasys}?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${BD_USER_NAME:root}
    password: ${BD_USER_PASSWORD:root}
  flyway:
    locations:
      - classpath:META-INF/db/migration
      - classpath:META-INF/db/testdata
    enabled: true
  jpa:
    mapping-resources: META-INF/orm.xml
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:keystores/bonnasys_public_key.pem

bonnafood:
  security:
    disabled: false
    default-user-id-if-disabled: 0919df77-ba6d-4214-acc9-70582db6fef5

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger
    operationsSorter: method
  show-actuator: true
