spring:
  datasource:
    url: jdbc:mysql://${DB_URL:localhost:3306}/${BD_SCHEMA:bonnasys}?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${BD_USER_NAME:root}
    password: ${BD_USER_PASSWORD:root}
  flyway:
    locations:
      - classpath:META-INF/db/migration
      - classpath:META-INF/db/testdata
    enabled: true
  jpa:
    mapping-resources: META-INF/orm.xml
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:keystores/bonnasys_public_key.pem

bonnafood:
  storage:
    type: S3
    local:
      user-avatar-directory: ${HOME}/estudos/avatares
    S3:
      bucket: bonnafood
      region: sa-east-1
      user-avatar-directory: users/avatar
      profile: bonnafood

  security:
    disabled: false
    default-user-id-if-disabled: 0919df77-ba6d-4214-acc9-70582db6fef5

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    oauth:
      client-id: bonnafood
      client-secret: web123
    path: /swagger
    operationsSorter: method
  show-actuator: true

opendocument:
  contact-email: contato@bonnafood.com.br
  contact-name: Contato Bonnafood :)
  module: Bonnafood
  api-version: 1.0
  description: "Uma descrição breve do documento"
  contact-url: https://bonnafood.com.br


resilience4j:
  circuitbreaker:
    instances:
      selectUserService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

