spring:
  datasource:
    url: jdbc:mysql://${DB_URL:localhost:3306}/${BD_SCHEMA:bonnafood}?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${BD_USER_NAME:root}
    password: ${BD_USER_PASSWORD:root}
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/testdata
  jpa:
    mapping-resources: META-INF/orm.xml
    show-sql: true

bonnafood:
  security:
    disabled: false
    default-user-id-if-disabled: 0919df77-ba6d-4214-acc9-70582db6fef5
    signingKey: cEyxABUMcnCqhrR6rVkBxPayRkTJg2DqkB69
    algorithm: HmacSHA256

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger
    operationsSorter: method
  show-actuator: true
